### PR TITLE
Updates and fixes

### PR DESCRIPTION
**Pull request by roman-khimov**

### CODE REVIEW

**Comment by vvarg229** [comment]
It seems that you need to change SecondsPerBlock to TimePerBlock in the Makefile too:
https://github.com/nspcc-dev/neofs-dev-env/blob/master/Makefile#L209

**Comment by roman-khimov** [comment]
Fixed.

**Review by vvarg229 — APPROVED** [review]

**Comment by vvarg229** [comment]
@roman-khimov can I assign this PR to myself and merge it?
Right now it's not assigned to anyone.

**Comment by roman-khimov** [comment]
Well, it doesn't need to be, I'd just wait for @cthulhu-rider to take a look at it.

**Pull request merged**
